<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LaptopAZ.Models\LaptopAZ.Models.csproj" />
    <ProjectReference Include="..\LaptopAZ.DTO\LaptopAZ.DTO.csproj" />
    <ProjectReference Include="..\LaptopAZ.Helpers\LaptopAZ.Helpers.csproj" />
    <ProjectReference Include="..\LaptopAZ.Repository\LaptopAZ.Repository.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>